"""Trim a real pipeline output into a committable contract sample.

    python scripts/make_contract_sample.py --run-id <RUN_ID> \
        --out docs/samples/output-document-v4.sample.json

A real document is 3+ MB, almost all of it embedding floats, and lives under the
gitignored data/. Other teams need the SHAPE, not the payload: this keeps one
item of each type, truncates vectors and term-frequency maps, and shortens long
text, so the result is small enough to commit and read.

Every key is preserved. Truncated values are marked with a sibling `_truncated`
note so nobody mistakes the sample for a complete document.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any
import argparse
import glob
import json

VECTOR_KEEP = 4
TF_KEEP = 5
TEXT_KEEP = 220


def trim_text(value: str, keep: int = TEXT_KEEP) -> str:
    return value if len(value) <= keep else value[:keep] + f"… [+{len(value) - keep} chars]"


def trim_item(item: dict[str, Any]) -> dict[str, Any]:
    out = json.loads(json.dumps(item, ensure_ascii=False))
    for embedding in out.get("embeddings") or []:
        values = embedding.get("values") or []
        if len(values) > VECTOR_KEEP:
            embedding["values"] = [round(v, 6) for v in values[:VECTOR_KEEP]]
            embedding["_truncated"] = f"{len(values)} floats in a real document"
    lexical = out.get("lexical")
    if isinstance(lexical, dict) and isinstance(lexical.get("tf"), dict):
        tf = lexical["tf"]
        if len(tf) > TF_KEEP:
            lexical["tf"] = dict(list(tf.items())[:TF_KEEP])
            lexical["_truncated"] = f"{len(tf)} distinct terms in a real document"
    content = out.get("content")
    if isinstance(content, dict):
        for key, value in content.items():
            if isinstance(value, str):
                content[key] = trim_text(value)
    return out


def trim_content_block(content: dict[str, Any]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key, value in content.items():
        if isinstance(value, str):
            out[key] = trim_text(value)
        elif isinstance(value, list):
            out[key] = ([json.loads(trim_json(value[0]))] + [f"… [+{len(value) - 1} more]"]) if value else []
        else:
            out[key] = value
    return out


def trim_json(value: Any) -> str:
    text = json.dumps(value, ensure_ascii=False)
    return text if len(text) <= 400 else json.dumps({"_truncated": trim_text(text, 300)}, ensure_ascii=False)


def build(source: Path) -> dict[str, Any]:
    document = json.loads(source.read_text(encoding="utf-8"))
    items = document["retrieval"]["items"]

    # One of each type, so every content shape is represented.
    by_type: dict[str, dict[str, Any]] = {}
    for item in items:
        by_type.setdefault(item["type"], item)
    counts = {t: sum(1 for i in items if i["type"] == t) for t in by_type}

    stats = dict(document["retrieval"]["lexical_stats"])
    if isinstance(stats.get("df"), dict) and len(stats["df"]) > TF_KEEP:
        df = stats["df"]
        stats["df"] = dict(list(df.items())[:TF_KEEP])
        stats["_truncated"] = f"{len(df)} distinct terms in a real document"

    return {
        "_sample": {
            "note": "Shape reference for output-document-v4. Values are truncated; "
                    "see `_truncated` markers. Generated by scripts/make_contract_sample.py.",
            "this_is": "ONE element of the `documents` array in the /v1/dataeng response.",
            "wire_shape": {
                "POST /v1/dataeng": {
                    "metadata": "<run-level metadata.json>",
                    "documents": ["<this object>", "… one per document"],
                },
                "note": "src/api/output.py returns the on-disk document artifacts "
                        "verbatim; the indexing job reads response['documents'] and "
                        "persists each element's document/content/retrieval blocks.",
            },
            "real_document": {"items_total": len(items), "items_by_type": counts},
            "consumed_by": {
                "document": "documents",
                "content": "document_contents (one row per key)",
                "retrieval.items[]": "document_embeddings (one row per item)",
                "retrieval.lexical_stats": "document_lexical_stats",
            },
        },
        "contract_version": document["contract_version"],
        "document": document["document"],
        "content": trim_content_block(document["content"]),
        "retrieval": {
            "items": [trim_item(item) for item in by_type.values()],
            "lexical_stats": stats,
        },
        "lineage": document["lineage"],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--out", default="docs/samples/output-document-v4.sample.json")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    matches = sorted(glob.glob(str(root / "data" / "output" / args.run_id / "documents" / "*.json")))
    if not matches:
        raise SystemExit(f"no output documents for run {args.run_id}")

    out_path = root / args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)
    sample = build(Path(matches[0]))
    out_path.write_text(json.dumps(sample, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"source : {matches[0]}  ({Path(matches[0]).stat().st_size / 1e6:.1f} MB)")
    print(f"sample : {out_path}  ({out_path.stat().st_size / 1024:.1f} KB)")
    print(f"items  : {sample['_sample']['real_document']['items_by_type']}")


if __name__ == "__main__":
    main()
